# -*- coding: utf-8 -*-
#
"""
We use sphinx to integrate docstrings of individual modules into a single
README.rst file, which is required by PyPI website. This is a simple sphinx
configuration file based on the one generated by "sphinx-quickstart" command.
Those unnecessary options in the original file have been removed to make it
more readable.

The following command needs to be executed in django-genes directory to
generate the integrated README.rst:

    sphinx-build -E -b rst sphinx .  # MUST be run in django-genes directory!

 * "-E": sphinx-build will NOT use any saved environment.
   (When this option is not specified, "sphinx-build" command sometimes throws
   the following AttributeError exception:
     BuildEnvironment instance has no attribute 'source_suffix'
   More details can be found at:
   http://www.sphinx-doc.org/en/stable/invocation.html#invocation-of-sphinx-build
 * "-b rst": the output format is rst;
 * "sphinx": the input directory;
 * ".": the output file (README.rst) will be put in current directory.
"""

import sys
import os

sys.path.insert(0, os.path.abspath('.'))
# Define DJANGO_SETTINGS_MODULE so that django management commands (see below)
# can be imported.
os.environ['DJANGO_SETTINGS_MODULE'] = 'django_settings'

# Import django managewment commands, whose docstrings will be requested by
# sphinx/README.rst and eventually integrated into ../README.rst.
sys.path.insert(0, os.path.abspath('../genes/management/commands'))
import genes_add_xrdb
import genes_load_geneinfo
import genes_load_uniprot
import genes_load_wb
import genes_load_gene_history

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
#
# "autodoc" extension is enabled to request docstrings from other modules.
# See: http://www.sphinx-doc.org/en/stable/ext/autodoc.html
#
# "napoleon" extension is enabled to support Google and NumPy styles.
# See: http://www.sphinx-doc.org/en/stable/ext/napoleon.html
#
# "sphinxcontrib.restbuilder" is a separate package installed by pip to
# generate file in rst format. The "-b rst" option in "sphinx-build" command
# won't be supported without this package. See:
# https://pypi.python.org/pypi/sphinxcontrib-restbuilder
#
extensions = [
    'sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinxcontrib.restbuilder'
]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master document.
master_doc = 'README'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
